#!/bin/bash

#SBATCH --time=23:00:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --mem=32GB
#SBATCH --job-name=train_mv2nv

ml TensorFlow/1.10.1-fosscuda-2018a-Python-2.7.14

source venv/bin/activate

python -u trainer.py  --batch_size 8 --dataset ship --num_input 4